### ISSUE TITLE
Create an account in AWS

### ISSUE THREAD

**Issue by lmilbaum** [royhershko/nexus#3]

**Comment by royhershko** [comment]
i will Follow the steps from here
[https://docs.aws.amazon.com/lambda/latest/dg/setup.html](url)

**Comment by royhershko** [comment]
I have now free account in AWS

**Comment by royhershko** [comment]
to do for me : read **HOW TO**
[https://aws.amazon.com/getting-started/tutorials/](url)

**Comment by lmilbaum** [comment]
I think you can close this issue. You have an account in AWS.
